### ISSUE TITLE
Unable to get items from config when using Add-FileConfigurationSource -Format StringData

### ISSUE THREAD

**Issue by gjonespf** [platta/PSConfig#1]
Using a pretty standard looking String file:
.env
```
BUILD_CAUSE = MANUALTRIGGER
BUILD_CAUSE_MANUALTRIGGER = true
BUILD_DISPLAY_NAME = #35
BUILD_ID = 35
```

And the code:

```    
Clear-ConfigurationSource
Add-FileConfigurationSource -Path ".env" -Format StringData -Verbose
Get-ConfigurationItem -Key "BUILD_ID " -Verbose
```

You'll get no results.  This is due to the fact that Get-ConfigurationItem is expecting a object with properties, but the function ConvertFrom-StringData which is used on the import returns a hashtable. Not sure if this is just a v5 thing.

[ConvertFrom-StringData](https://msdn.microsoft.com/en-us/powershell/reference/5.1/microsoft.powershell.utility/convertfrom-stringdata)

$PSVersionTable
```
Name                           Value
----                           -----
PSVersion                      5.1.14393.693
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.693
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by platta** [comment]
Thanks for spotting this, and for the timely fix! I always use JSON files, so it's possible this was busted before V5 was released. Hope you're finding the module useful.

**Comment by gjonespf** [comment]
Yeah, very useful so far.  I'm currently playing around with some changes to allow simple overrides, but will give it some time to settle before I throw a PR your way.
